pipeline {
      agent any
      stages {
        stage('Fetch Repo') {
          steps {
            sh 'git https://github.com/alex4512/spring-data-h2-dev-hal-docker.git'
            sh 'ls'
          }
        }
    }
 }
